version: '2.2'
services:
    redis:
        image: 'redis:5.0.5'
        # command: redis-server --requirepass redispass

    postgres:
        image: postgres:9.6
        env_file:
            - postgres.env
        volumes:
             - ./pgdata:/var/lib/postgresql/data/pgdata

    webserver:
        image: airflow-docker
        restart: always
        depends_on:
            - postgres
            - redis
        env_file:
            - airflow.env
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: airflow-docker
        restart: always
        depends_on:
            - redis
        env_file:
            - airflow.env
        ports:
            - "5555:5555"
        command: celery flower

    scheduler:
        image: airflow-docker
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        env_file:
            - airflow.env
        command: scheduler

    worker:
        image: airflow-docker
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        env_file:
            - airflow.env
        command: celery worker